kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    labels:
      role: control
      env: dev
  - role: worker
    labels:
      role: worker
      env: dev
  - role: worker
    labels:
      role: worker
      env: dev
